version: '3.8'

services:
  web:
    build:
      context: ./transformwiki
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./transformwiki/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_transformwiki
      - POSTGRES_PASSWORD=db_transformwiki_pw
      - POSTGRES_DB=db_transformwiki_dev
      
  # celery:
  #   build:
  #     context: ./transformwiki
  #     dockerfile: Dockerfile
  #   command: celery -A app worker -B -l INFO
  #   volumes:
  #     - ./transformwiki/:/usr/src/app/
  #   depends_on:
  #     - web
  #     - db
  #     - redis

  redis:
    image: "redis:alpine"


volumes:
  postgres_data:

